export const ErrorCode = {
  API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  BAD_GATEWAY: 'BAD_GATEWAY',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SERVER_ERROR: 'SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
};
